=== svn2github/hwk/META-INF/guzz.dtd
<!--
	Guzz main config DTD, version 1.0
	Authors: Liu Kaixuan (liukaixuan@gmail.com)

	<!DOCTYPE guzz-configs PUBLIC "-//GUZZ//MAIN CONFIG DTD//EN" "http://www.guzz.org/dtd/guzz.dtd">
-->

<!ELEMENT guzz-configs (
properties?, (config-server? | tran? | dialect| service | import | business | sqlMap | orm)*
)>

<!ELEMENT properties EMPTY>
<!ATTLIST properties file CDATA #REQUIRED>


<!ELEMENT config-server (server+)>
<!ELEMENT server (param*)>
<!ATTLIST server class CDATA #REQUIRED>
<!ELEMENT param EMPTY>
<!ATTLIST param name CDATA #REQUIRED>
<!ATTLIST param value CDATA #REQUIRED>


<!ELEMENT tran (dbgroup+)>
<!ELEMENT dbgroup EMPTY>
<!ATTLIST dbgroup name CDATA "default">
<!ATTLIST dbgroup masterDBConfigName CDATA #IMPLIED>
<!ATTLIST dbgroup slaveDBConfigName CDATA #IMPLIED>
<!ATTLIST dbgroup dialectName CDATA #IMPLIED>


<!ELEMENT dialect (type*)>
<!ATTLIST dialect name CDATA "default">
<!ATTLIST dialect class CDATA #REQUIRED>
<!ELEMENT type EMPTY>
<!ATTLIST type name CDATA #REQUIRED>
<!ATTLIST type class CDATA #REQUIRED>


<!ELEMENT service EMPTY>
<!ATTLIST service name CDATA #REQUIRED>
<!ATTLIST service configName CDATA #REQUIRED>
<!ATTLIST service class CDATA #REQUIRED>


<!ELEMENT import EMPTY>
<!ATTLIST import resource CDATA #REQUIRED>


<!ELEMENT business EMPTY>
<!ATTLIST business name CDATA #REQUIRED>
<!ATTLIST business dbgroup CDATA "default">
<!ATTLIST business class CDATA #IMPLIED>
<!ATTLIST business interpret CDATA #IMPLIED>
<!ATTLIST business file CDATA #REQUIRED>


<!ELEMENT sqlMap ((select | update | orm)*)>
<!ATTLIST sqlMap dbgroup CDATA "default">

<!ELEMENT select (#PCDATA)>
<!ATTLIST select id ID #REQUIRED>
<!ATTLIST select orm CDATA #REQUIRED>
<!ATTLIST select dbgroup CDATA "default">

<!ELEMENT update (#PCDATA)>
<!ATTLIST update id ID #REQUIRED>
<!ATTLIST update orm CDATA #REQUIRED>
<!ATTLIST update dbgroup CDATA "default">

<!ELEMENT orm (result*)>
<!ATTLIST orm id CDATA #REQUIRED>
<!ATTLIST orm class CDATA #REQUIRED>
<!ATTLIST orm dbgroup CDATA "default">

<!ELEMENT generator (param*)>
<!ATTLIST generator class CDATA "native">

<!ELEMENT result EMPTY>
<!ATTLIST result property CDATA #REQUIRED>
<!ATTLIST result column CDATA #REQUIRED>
<!ATTLIST result type CDATA #IMPLIED>
<!ATTLIST result null CDATA #IMPLIED>
<!ATTLIST result loader CDATA #IMPLIED>

=== svn2github/hwk/WebRoot/WEB-INF/guzz.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE guzz-configs PUBLIC "-//GUZZ//DTD MAIN CONFIG//EN" "http://guzz.xiu666.com/dtd/guzz.dtd">

<guzz-configs>

	<!-- 从Properties 文件中读取配置项，替换guzz.xml文档中的$xxx参数 -->
	<properties file="guzz.properties" />	
	
	<config-server>
		<server class="org.guzz.config.LocalFileConfigServer">
			<param name="resource" value="guzz_app.properties" />
		</server>
	</config-server>
	
	<dialect class="org.guzz.dialect.H2Dialect" />
	
	<tran>
		<dbgroup name="default" masterDBConfigName="masterDB"  />
		<dbgroup name="updateDB" masterDBConfigName="updateMasterDB" />
		<dbgroup name="logDB" masterDBConfigName="updateMasterDB" />
	</tran>	
	
	<business name="guzzSlowUpdate" dbgroup="updateDB" file="classpath://org/guzz/service/core/IncUpdateBusiness.hbm.xml" />
	<business name="user" file="classpath://org/guzz/test/User.hbm.xml" />
	<business name="article" file="classpath://org/guzz/test/Article.hbm.xml" />
	<business name="articleCount" file="classpath://org/guzz/test/ArticleCount.hbm.xml" />
	
	<sqlMap>
		<select id="selectUser" orm="user">
			select * from @@user
			 where 
			 	@id = :id 
		</select>
	
		<update id="updateUserFavCount" orm="userObjectMap">
			update @@user set @favCount = favCount + 1
		</update>
		
		<select id="selectUsers" orm="userObjectMap">
			select @id, @name, @vip, @favCount from @@user
		</select>
				
		<orm id="userObjectMap" class="org.guzz.test.UserModel">
			<generator  class="native" >
				<param name="column" value="pk" />
			</generator>
			
			<result property="id" column="pk"/>
		    <result property="name" column="userName"/>
		    <result property="favCount" column="FAV_COUNT"/>
		    <result property="vip" column="VIP_USER"/>
		</orm>
		
	</sqlMap>

</guzz-configs>

=== svn2github/hwk/test/guzzmain_test1_annotation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE guzz-configs PUBLIC "-//GUZZ//DTD MAIN CONFIG//EN" "http://www.guzz.org/dtd/guzz.dtd">

<guzz-configs>
	
	<config-server>
		<server class="org.guzz.config.LocalFileConfigServer">
			<param name="resource" value="guzz_test2.properties" />
		</server>
	</config-server>
	
	<dialect class="org.guzz.dialect.H2Dialect"></dialect>
	<dialect name="mysql5dialect" class="org.guzz.dialect.Mysql5Dialect" />
	<dialect name="oracle10gdialect" class="org.guzz.dialect.Oracle10gDialect" />
	
	<tran>
		<dbgroup name="default" masterDBConfigName="masterDB" />
		<dbgroup name="mysql" masterDBConfigName="mysqlDB" dialectName="mysql5dialect" />
		<dbgroup name="oracle" masterDBConfigName="oracleDB" dialectName="oracle10gdialect" />
	</tran>
	
	<service name="onlyForTest" configName="onlyForTestConfig" class="org.guzz.test.sample.SampleTestService" />
	<service name="onlyForTest2" configName="onlyForTest2Config" dependsOn="onlyForTest1" class="org.guzz.test.sample.SampleTestService2" />
	
	<import resource="include/part2.xml" />

	<a-business name="user" dbgroup="default" class="org.guzz.test.User"/>
	<a-business name="book" class="org.guzz.test.Book" />
	<a-business name="userInfo" dbgroup="oracle" class="org.guzz.test.UserInfo" />
	<a-business name="userInfo2" dbgroup="default" class="org.guzz.test.UserInfoH2" />
	<a-business name="comment" dbgroup="default" class="org.guzz.test.Comment"/>
	<a-business name="cargo" class="org.guzz.test.shop.Cargo" />
	<a-business name="sp" class="org.guzz.test.shop.SpecialProperty" />
	
	<sqlMap dbgroup="default">
		<select id="selectUser" orm="user" dbgroup="default">
			select * from @@user
			 where 
			 	@id = :id 
		</select>
		
		<select id="selectUserByName" orm="user">
			select @id, @userName, @vip, @password from @@user where @userName = :userName
		</select>
	
		<update id="updateUserFavCount" orm="userObjectMap">
			update @@user set @favCount = favCount + 1
		</update>
		
		<select id="selectUsers" orm="userObjectMap">
			select @id, @name, @vip, @favCount from @@user
		</select>
		
		<select id="listCommentsByName" orm="commentMap">
			select * from @@commentMap where @userName = :userName
		</select>
				
		<orm id="userObjectMap" class="org.guzz.test.UserModel">
			<result property="id" column="pk"/>
		    <result property="name" column="userName"/>
		    <result property="favCount" column="FAV_COUNT"/>
		    <result property="vip" column="VIP_USER"/>
		</orm>
		
		<orm id="commentMap" class="org.guzz.test.Comment" table="TB_COMMENT" shadow="org.guzz.test.CommentShadowView">
			<result property="id" column="id" type="int"/>
		    <result property="userId" column="userId" type="int"/>
		    <result property="userName" column="userName" type="string" />
		    <result property="createdTime" column="createdTime" type="datetime" />
		</orm>
	</sqlMap>

</guzz-configs>

=== svn2github/hwk/test/guzzmain_test1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE guzz-configs PUBLIC "-//GUZZ//DTD MAIN CONFIG//EN" "http://www.guzz.org/dtd/guzz.dtd">

<guzz-configs>

	<!-- 从Properties 文件中读取配置项，替换guzz.xml文档中的$xxx参数 -->
	<properties file="guzz.properties" />
	
	<config-server>
		<server class="org.guzz.config.LocalFileConfigServer">
			<param name="resource" value="guzz_test2.properties" />
		</server>
	</config-server>
	
	<tran>
		<dbgroup name="default" masterDBConfigName="masterDB" />
		<dbgroup name="log" masterDBConfigName="masterDB" dialectName="mysql5dialect" />
	</tran>
	
	<service name="onlyForTest" configName="onlyForTestConfig" class="org.guzz.test.sample.SampleTestService" />
	<service name="onlyForTest2" configName="onlyForTest2Config" class="org.guzz.test.sample.SampleTestService2" />
	
	<import resource="include/part2.xml" />

	<business name="user" dbgroup="default" class="org.guzz.test.User" interpret="" file="classpath:org/guzz/test/User.hbm.xml" />
	<business name="book" class="org.guzz.test.Book" file="classpath:org/guzz/test/Book.hbm.xml" />
	
	<dialect class="org.guzz.dialect.H2Dialect"></dialect>
	<dialect name="mysql5dialect" class="org.guzz.dialect.Mysql5Dialect" />
	
	<sqlMap dbgroup="default">
		<select id="selectUser" orm="user" dbgroup="default">
			select * from @@user
			 where 
			 	@id = :id 
		</select>
	
		<update id="updateUserFavCount" orm="userObjectMap">
			update @@user set @favCount = favCount + 1
		</update>
		
		<select id="selectUsers" orm="userObjectMap">
			select @id, @name, @vip, @favCount from @@user
		</select>
				
		<orm id="userObjectMap" class="org.guzz.test.UserModel">
			<result property="id" column="pk"/>
		    <result property="name" column="userName"/>
		    <result property="favCount" column="FAV_COUNT"/>
		    <result property="vip" column="VIP_USER"/>
		</orm>
		
	</sqlMap>

</guzz-configs>
